Repository nutanix-cloud-native/packer-plugin-nutanix, pull requests merged in 2022-11, with the labels that each got.

#64 fix CVE-2022-32149
  go.mod
  go.sum
Labels: dependencies

#58 overwrite images
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/driver.go
  builder/nutanix/step_copy_image.go
  example/source.nutanix.pkr.hcl
Labels: enhancement

#59 Add source image url
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/driver.go
  builder/nutanix/step_build_vm.go
Labels: enhancement

#54 add CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: ignore-for-release

#70 apply go fmt
  builder/nutanix/config.go
  builder/nutanix/driver.go
  builder/nutanix/step_build_vm.go
  builder/nutanix/step_shutdown_vm.go
Labels: ignore-for-release

#71 artefact identification improvement
  builder/nutanix/builder.go
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/driver.go
  builder/nutanix/step_copy_image.go
Labels: enhancement

#57 Documentation
  docs/builders/overview.mdx
  docs/builders/plugin.mdx
Labels: documentation

#72 activate docs release
  .goreleaser.yml
Labels: ignore-for-release

#73 Fix/docs link
  docs/builders/overview.mdx
  docs/builders/plugin.mdx
Labels: documentation, ignore-for-release

#74 fix releaser config
  .goreleaser.yml
Labels: ignore-for-release
