Repository nutanix-cloud-native/packer-plugin-nutanix, pull requests merged in 2022-07, with the labels that each got.

#13 upload image only to dedicated PE Cluster
  .gitignore
  builder/nutanix/driver.go
  builder/nutanix/step_build_vm.go
  builder/nutanix/step_copy_image.go
  builder/nutanix/utils.go
Labels: bug

#19 add CI improvements
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/integration.yml
  .github/workflows/release.yml
  Makefile
  README.md
Labels: ignore-for-release

#20 fix vm declaration
  builder/nutanix/driver.go
Labels: bug

#21 Update README.md
  README.md
Labels: ignore-for-release

#29 fix doc and remove scaffold
  README.md
  docs/README.md
  docs/builders/builder-name.mdx
  docs/datasources/datasource-name.mdx
  docs/post-processors/postprocessor-name.mdx
  docs/provisioners/provisioner-name.mdx
Labels: documentation

#31 add CPU support
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/driver.go
Labels: enhancement

#32 add UEFI boot type
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/driver.go
Labels: enhancement
