Repository nutanix-cloud-native/packer-plugin-nutanix, pull requests merged in 2025-06, with the labels that each got.

#238 fix(build): Add pull_request_target check_approvals guardrails
  .github/workflows/synopsys.yaml
Labels: integration-test

#252 Add boot_command support
  .web-docs/README.md
  .web-docs/components/builder/nutanix/README.md
  Makefile
  README.md
  builder/nutanix/builder.go
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/driver.go
  builder/nutanix/step_build_vm.go
  builder/nutanix/step_vnc_boot_command.go
  builder/nutanix/step_vnc_connect.go
  builder/nutanix/step_wait_for_ip.go
  builder/nutanix/step_wait_for_ip.hcl2spec.go
  docs-partials/builder/nutanix/WaitIpConfig-not-required.mdx
  docs/README.md
  docs/builders/nutanix.mdx
  example/README.md
  example/build.nutanix.pkr.hcl
  example/scripts/cloud-init/autoinstall-ubuntu.yaml
  example/source.nutanix.pkr.hcl
  example/variables.pkr.hcl
  go.mod
  go.sum
  version/version.go
Labels: enhancement

#254 Fix IP wait workflow
  .web-docs/README.md
  .web-docs/components/builder/nutanix/README.md
  README.md
  builder/nutanix/builder.go
  builder/nutanix/config.go
  builder/nutanix/driver.go
  builder/nutanix/step_vnc_boot_command.go
  builder/nutanix/step_vnc_connect.go
  builder/nutanix/step_wait_for_ip.go
  docs/README.md
  docs/builders/nutanix.mdx
  example/init/plugin.pkr.hcl
  version/version.go
Labels: bug

#247 Add support for OVA export
  .web-docs/components/builder/nutanix/README.md
  builder/nutanix/builder.go
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/driver.go
  builder/nutanix/step_create_ova.go
  builder/nutanix/step_export_ova.go
  docs/builders/nutanix.mdx
Labels: enhancement

#258 quick ova fix
  .web-docs/components/builder/nutanix/README.md
  builder/nutanix/config.go
  builder/nutanix/driver.go
  builder/nutanix/step_export_ova.go
  docs/builders/nutanix.mdx
Labels: bug

#259 update ISO doc
  .web-docs/components/builder/nutanix/README.md
  docs/builders/nutanix.mdx
Labels: bug

#262 Add `image_skip` option to skip image creation step
  .web-docs/components/builder/nutanix/README.md
  builder/nutanix/builder.go
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/step_copy_image.go
  docs/builders/nutanix.mdx
Labels: enhancement

#263 Add support for VM template creation
  .web-docs/components/builder/nutanix/README.md
  builder/nutanix/builder.go
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/driver.go
  builder/nutanix/step_create_image.go
  builder/nutanix/step_create_ova.go
  builder/nutanix/step_create_template.go
  docs/builders/nutanix.mdx
  go.mod
Labels: enhancement

#253 Add secure_boot support
  .web-docs/components/builder/nutanix/README.md
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/driver.go
  docs/builders/nutanix.mdx
  example/source.nutanix.pkr.hcl
  go.mod
  go.sum
Labels: enhancement

#264 improve config verification for vTPM
  builder/nutanix/config.go
Labels: enhancement

#267 ignore prism central cluster
  builder/nutanix/driver.go
  builder/nutanix/utils.go
Labels: enhancement

#270 fix winrm_host issue
  .web-docs/components/builder/nutanix/README.md
  builder/nutanix/builder.go
  builder/nutanix/config.go
  builder/nutanix/ssh.go
  builder/nutanix/step_shutdown_vm.go
  builder/nutanix/utils.go
  docs/builders/nutanix.mdx
  example/windows/build.nutanix.pkr.hcl
  example/windows/files/autounattend.xml
  example/windows/files/scripts/ConfigureRemotingForAnsible.ps1
  example/windows/files/scripts/EnableWinRMforPacker.ps1
  example/windows/files/scripts/SetupComplete.cmd
  example/windows/files/scripts/StaticIP.ps1
  example/windows/settings.auto.pkrvars.hcl
  example/windows/source.nutanix.pkr.hcl
  example/windows/variables.pkr.hcl
Labels: bug

#239 adding local iso upload
  builder/nutanix/config.go
  builder/nutanix/config.hcl2spec.go
  builder/nutanix/step_build_vm.go
Labels: enhancement
